//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace labelPrint.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class siixsem_lblTemplates_t
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public siixsem_lblTemplates_t()
        {
            this.siixsem_lblModels_td = new HashSet<siixsem_lblModels_td>();
        }
    
        public int se_id_label { get; set; }
        public int se_id_zpl { get; set; }
        public int se_id_dm { get; set; }
    
        public virtual siixsem_datamatrix_t siixsem_datamatrix_t { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<siixsem_lblModels_td> siixsem_lblModels_td { get; set; }
        public virtual siixsem_lblZPL_t siixsem_lblZPL_t { get; set; }
    }
}
