//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace labelPrint.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class siixsem_flxb_t
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public siixsem_flxb_t()
        {
            this.siixsem_flxsModel_td = new HashSet<siixsem_flxsModel_td>();
            this.siixsem_flxsModel_led2_td = new HashSet<siixsem_flxsModel_led2_td>();
        }
    
        public int se_id_fb { get; set; }
        public string se_description { get; set; }
        public string se_flx_lbl { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<siixsem_flxsModel_td> siixsem_flxsModel_td { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<siixsem_flxsModel_led2_td> siixsem_flxsModel_led2_td { get; set; }
    }
}
