//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace labelPrint.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class siixsem_colorsb_td
    {
        public int se_id { get; set; }
        public int se_id_colorb { get; set; }
        public int se_id_model { get; set; }
        public int se_id_lblTag { get; set; }
    
        public virtual siixsem_lblTagColor_t siixsem_lblTagColor_t { get; set; }
        public virtual siixsem_models_t siixsem_models_t { get; set; }
        public virtual siixsem_colorb_t siixsem_colorb_t { get; set; }
    }
}
