//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace labelPrint.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class siixsem_failInsOr_t
    {
        public int se_id { get; set; }
        public string se_dj_number { get; set; }
        public int se_trans_qty { get; set; }
        public System.DateTime se_created { get; set; }
        public string se_status { get; set; }
        public string se_line { get; set; }
    }
}
