//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace labelPrint.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class siixsem_ledSimos_t
    {
        public int INVENTORY_ITEM_ID { get; set; }
        public string DESCRIPTION { get; set; }
        public string SEGMENT1 { get; set; }
    }
}
