//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace labelPrint.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class siixsem_pcbSerials_td
    {
        public int se_id { get; set; }
        public int se_id_dj { get; set; }
        public string se_serial { get; set; }
        public int se_release_scaned { get; set; }
        public int se_spg_scaned { get; set; }
        public int se_id_line { get; set; }
        public int se_upload { get; set; }
        public int se_print_folio { get; set; }
        public int se_id_side { get; set; }
        public int se_count { get; set; }
        public string se_serTop { get; set; }
        public string se_serBot { get; set; }
        public int se_mu_scaned { get; set; }
        public int se_fct_scaned { get; set; }
        public int se_jpacking_scaned { get; set; }
    
        public virtual siixsem_DjHist_t siixsem_DjHist_t { get; set; }
    }
}
