//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace labelPrint.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class siixsem_datamatrix_t
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public siixsem_datamatrix_t()
        {
            this.siixsem_lblTemplates_t = new HashSet<siixsem_lblTemplates_t>();
        }
    
        public int se_id_dm { get; set; }
        public string se_description { get; set; }
        public int se_id_density { get; set; }
        public int se_id_size { get; set; }
    
        public virtual siixsem_densities_t siixsem_densities_t { get; set; }
        public virtual siixsem_lblSizes_t siixsem_lblSizes_t { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<siixsem_lblTemplates_t> siixsem_lblTemplates_t { get; set; }
    }
}
