//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace labelPrint.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class siixsem_users_t
    {
        public int se_id_user { get; set; }
        public string se_name { get; set; }
        public string se_pass { get; set; }
        public int se_id_rol { get; set; }
    
        public virtual siixsem_user_role_t siixsem_user_role_t { get; set; }
    }
}
