//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace labelPrint.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class siixsem_VoltsModel_td
    {
        public int se_id_detail { get; set; }
        public int se_id_model { get; set; }
        public int se_id_volt { get; set; }
    
        public virtual siixsem_models_t siixsem_models_t { get; set; }
        public virtual siixsem_voltageb_t siixsem_voltageb_t { get; set; }
    }
}
