//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace labelPrint.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class siixsem_djs_t
    {
        public int id_dj { get; set; }
        public string ASSEMBLY_DESC { get; set; }
        public string PAIR_FG_NAME { get; set; }
        public System.DateTime CREATED_DT { get; set; }
        public int DJ_QTY { get; set; }
        public string DJ_NO { get; set; }
        public string ASSEMBLY_NAME { get; set; }
    }
}
