//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace labelPrint.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class siixsem_models_t
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public siixsem_models_t()
        {
            this.siixsem_flxsModel_td = new HashSet<siixsem_flxsModel_td>();
            this.siixsem_sidesModel_td = new HashSet<siixsem_sidesModel_td>();
            this.siixsem_VoltsModel_td = new HashSet<siixsem_VoltsModel_td>();
            this.siixsem_colorsb_td = new HashSet<siixsem_colorsb_td>();
            this.siixsem_ldmModels_td = new HashSet<siixsem_ldmModels_td>();
            this.siixsem_ldmModels_td1 = new HashSet<siixsem_ldmModels_td>();
            this.siixsem_modFourLbls_td = new HashSet<siixsem_modFourLbls_td>();
            this.siixsem_modFourLbls_td1 = new HashSet<siixsem_modFourLbls_td>();
            this.siixsem_colorsb_led2_td = new HashSet<siixsem_colorsb_led2_td>();
            this.siixsem_flxsModel_led2_td = new HashSet<siixsem_flxsModel_led2_td>();
            this.siixsem_VoltsModel_led2_td = new HashSet<siixsem_VoltsModel_led2_td>();
        }
    
        public int se_id_model { get; set; }
        public string se_description { get; set; }
        public int se_id_family { get; set; }
        public int se_is_special { get; set; }
        public int se_valid { get; set; }
        public int se_serial_continuos { get; set; }
        public int se_two_led { get; set; }
        public int se_dfc_ifc { get; set; }
        public int se_four_sides { get; set; }
        public int se_cover_frame { get; set; }
        public float se_num_pcb { get; set; }
        public int se_laser_mark { get; set; }
        public int se_has_panelLbl { get; set; }
        public int se_is_ldm { get; set; }
        public int se_one_step { get; set; }
        public int se_two_step { get; set; }
        public int se_three_step { get; set; }
        public int se_xml { get; set; }
        public int se_is_pallet { get; set; }
    
        public virtual siixsem_families_t siixsem_families_t { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<siixsem_flxsModel_td> siixsem_flxsModel_td { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<siixsem_sidesModel_td> siixsem_sidesModel_td { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<siixsem_VoltsModel_td> siixsem_VoltsModel_td { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<siixsem_colorsb_td> siixsem_colorsb_td { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<siixsem_ldmModels_td> siixsem_ldmModels_td { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<siixsem_ldmModels_td> siixsem_ldmModels_td1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<siixsem_modFourLbls_td> siixsem_modFourLbls_td { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<siixsem_modFourLbls_td> siixsem_modFourLbls_td1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<siixsem_colorsb_led2_td> siixsem_colorsb_led2_td { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<siixsem_flxsModel_led2_td> siixsem_flxsModel_led2_td { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<siixsem_VoltsModel_led2_td> siixsem_VoltsModel_led2_td { get; set; }
    }
}
