//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace labelPrint.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class siixseem_event_log
    {
        public int se_id_log { get; set; }
        public int se_id_event { get; set; }
        public int se_id_user { get; set; }
        public string se_description { get; set; }
        public System.DateTime se_date_event { get; set; }
        public Nullable<int> se_id_spec { get; set; }
    
        public virtual siixseem_events_t siixseem_events_t { get; set; }
        public virtual siixsem_lblModel_spec_td siixsem_lblModel_spec_td { get; set; }
    }
}
